// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_amdMatrix_magma_chol
void cpp_amdMatrix_magma_chol(SEXP ptrA, const int type_flag, int ctx_id);
RcppExport SEXP gpuRclmagma_cpp_amdMatrix_magma_chol(SEXP ptrASEXP, SEXP type_flagSEXP, SEXP ctx_idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type ptrA(ptrASEXP);
    Rcpp::traits::input_parameter< const int >::type type_flag(type_flagSEXP);
    Rcpp::traits::input_parameter< int >::type ctx_id(ctx_idSEXP);
    cpp_amdMatrix_magma_chol(ptrA, type_flag, ctx_id);
    return R_NilValue;
END_RCPP
}
