# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_amdMatrix_magma_chol <- function(ptrA, type_flag, ctx_id) {
    invisible(.Call('gpuRclmagma_cpp_amdMatrix_magma_chol', PACKAGE = 'gpuRclmagma', ptrA, type_flag, ctx_id))
}

